"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface Step {
  id: number;
  question: string;
  options?: string[];
  type: 'select' | 'text' | 'multi';
}

const steps: Step[] = [
  { id: 1, question: "What's your industry or main business area?", type: 'text' },
  { id: 2, question: "Rough company scale?", type: 'select' }, // special cased below for separate revenue + team
  { id: 3, question: "Biggest AI-related pain right now?", options: ["Too many tools, no clear wins", "Operations are manual and slow", "Marketing/leads not scaling", "Team overwhelmed by hype vs. results"], type: 'multi' },
  { id: 4, question: "Timeline for seeing real impact?", options: ["Next 30-60 days", "Next quarter", "6+ months"], type: 'select' },
];

export default function PlanningWizard() {
  const [currentStep, setCurrentStep] = useState(1);
  const [answers, setAnswers] = useState<Record<number, string | string[]>>({});
  const [generatedPlan, setGeneratedPlan] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [checkoutStep, setCheckoutStep] = useState<'plan' | 'checkout' | 'success'>('plan');
  const [checkoutEmail, setCheckoutEmail] = useState('');

  const current = steps.find(s => s.id === currentStep)!;

  const handleAnswer = (value: string) => {
    setAnswers(prev => {
      if (current.type === 'multi') {
        const currentVals = (prev[current.id] as string[]) || [];
        const newVals = currentVals.includes(value) 
          ? currentVals.filter(v => v !== value) 
          : [...currentVals, value];
        return { ...prev, [current.id]: newVals };
      }
      return { ...prev, [current.id]: value };
    });
  };

  const handleAnswerForScale = (field: 'revenue' | 'team', value: string, prevScale: any) => {
    setAnswers(prev => ({
      ...prev,
      [current.id]: {
        ...prevScale,
        [field]: value
      }
    }));
  };

  const next = () => {
    if (currentStep < steps.length) {
      setCurrentStep(currentStep + 1);
    } else {
      generatePlan();
    }
  };

  const prev = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  const generatePlan = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      const industry = answers[1] || 'your business';
      const scale = answers[2] as any;
      const size = scale ? `${scale.revenue || ''} revenue, ${scale.team || ''} team` : 'your size';
      const pains = (answers[3] as string[] || []).join(' + ') || 'core inefficiencies';
      const timeline = answers[4] || 'soon';

      const plan = `Initial AI Roadmap — generated by betterwithai system

For: ${industry} (${size})
Key pains: ${pains}
Timeline: ${timeline}

Prioritized wins (ROI ranked):
1. Quick-win automation: 18-30 hrs/mo back. Lead qualification or ops dispatch agent. High impact, low lift.
2. Process intelligence: AI surfaces patterns across your tools & data.
3. Client-facing leverage: Self-serve experiences or agents so you scale without adding headcount.

What the full Roadmap will include:
• Detailed audit of ops, marketing, tools
• Exact tools + build order with cost/benefit
• 60-min walkthrough call
• Written deliverable + 30-day support path

This site + Ops Leader just did the heavy planning lift. The paid Roadmap goes much deeper with your real data.`;

      setGeneratedPlan(plan);
      setIsGenerating(false);
      setCheckoutStep('plan');
    }, 1100);
  };

  const reset = () => {
    setCurrentStep(1);
    setAnswers({});
    setGeneratedPlan(null);
    setCheckoutStep('plan');
    setCheckoutEmail('');
  };

  if (generatedPlan) {
    return (
      <div className="max-w-[720px] mx-auto">
        <div className="mb-6">
          <div className="text-[#0A66C2] text-xs tracking-[2px] mb-1">YOUR PLAN</div>
          <h3 className="text-3xl font-semibold tracking-tight text-[#111]">The configurator built this for you.</h3>
        </div>

        <div className="bg-white border border-[#E5E5E3] p-8 rounded-3xl text-[14px] leading-relaxed text-[#333] font-mono whitespace-pre-wrap mb-8">
{generatedPlan}
        </div>

        <div className="text-center">
          <div className="space-y-3">
            <input
              type="email"
              placeholder="your@company.com (for instant portal access)"
              value={checkoutEmail}
              onChange={(e) => setCheckoutEmail(e.target.value)}
              className="w-full border border-[#E5E5E3] p-4 rounded-2xl text-base"
            />

            <button
              onClick={async () => {
                try {
                  const res = await fetch('/api/checkout', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                      offerId: 'readiness', // or 'coaching' / 'implementation' based on upsell choice
                      email: checkoutEmail,
                      answers,
                    }),
                  });
                  const data = await res.json();
                  if (data.url) {
                    window.open(data.url, '_blank');
                  }
                } catch (e) {
                  // Fallback
                  window.open(`https://buy.stripe.com/test_14k8wN2iL5iQ9cQ000?prefilled_email=${encodeURIComponent(checkoutEmail || '')}`, '_blank');
                }
                setTimeout(() => setCheckoutStep('success'), 900);
              }}
              className="btn-primary w-full text-lg py-4"
            >
              Complete purchase — $1,497 (AI Roadmap)
            </button>

            <div className="text-[11px] text-[#666] text-center">
              Self-serve. Instant portal access after payment. Money-back if we don't deliver 3+ concrete moves.
            </div>

            <a 
              href={`/portal?demoLogin=acme&newProject=true${checkoutEmail ? `&email=${encodeURIComponent(checkoutEmail)}` : ''}`}
              className="block text-xs underline text-[#888] hover:text-[#0A66C2]"
            >
              Or view the demo portal now (no charge)
            </a>
          </div>
          <div className="mt-3 text-xs text-[#666]">One click. Live in the portal immediately.</div>

          <button onClick={reset} className="mt-4 text-sm text-[#888] hover:text-black">Start over</button>
        </div>
      </div>
    );
  }

  const currentAnswer = answers[current.id];
  const isScaleStep = current.id === 2;
  const hasAnswer = isScaleStep 
    ? !!( (currentAnswer as any)?.revenue && (currentAnswer as any)?.team )
    : current.type === 'multi' 
      ? (currentAnswer as string[] || []).length > 0 
      : !!currentAnswer;

  return (
    <div className="max-w-[620px] mx-auto bg-white border border-[#E5E5E3] p-8 rounded-3xl">
      <div className="mb-8">
        <div className="text-[#0A66C2] text-xs tracking-[2px] mb-1">STEP {currentStep} OF {steps.length}</div>
        <h3 className="text-3xl font-semibold tracking-tight text-[#111]">{current.question}</h3>
      </div>

      <div className="space-y-3 mb-8">
        {current.type === 'text' && (
          <input 
            type="text" 
            className="w-full bg-[#FAFAF8] border border-[#E5E5E3] p-5 rounded-2xl text-lg placeholder:text-[#888] focus:outline-none focus:border-[#0A66C2]"
            placeholder="Type your answer..."
            value={(currentAnswer as string) || ''}
            onChange={(e) => handleAnswer(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter' && hasAnswer) next(); }}
          />
        )}

        {current.id === 2 && (
          <div className="space-y-6">
            {/* Revenue */}
            <div>
              <div className="text-sm text-[#666] mb-2">Annual revenue</div>
              {["Under $2M", "$2M–$10M", "$10M+"].map(option => {
                const selected = (currentAnswer as any)?.revenue === option;
                return (
                  <button
                    key={option}
                    onClick={() => {
                      const prev = (answers[2] as any) || {};
                      handleAnswerForScale('revenue', option, prev);
                    }}
                    className={`w-full text-left p-4 mb-2 rounded-2xl border text-base transition-all ${selected 
                      ? 'border-[#0A66C2] bg-[#F0F7FF] text-[#111]' 
                      : 'border-[#E5E5E3] hover:border-[#CCC] bg-white'}`}
                  >
                    {option}
                    {selected && ' ✓'}
                  </button>
                );
              })}
            </div>

            {/* Team size */}
            <div>
              <div className="text-sm text-[#666] mb-2">Team size</div>
              {["<10 people", "10-50 people", "50+ people"].map(option => {
                const selected = (currentAnswer as any)?.team === option;
                return (
                  <button
                    key={option}
                    onClick={() => {
                      const prev = (answers[2] as any) || {};
                      handleAnswerForScale('team', option, prev);
                    }}
                    className={`w-full text-left p-4 mb-2 rounded-2xl border text-base transition-all ${selected 
                      ? 'border-[#0A66C2] bg-[#F0F7FF] text-[#111]' 
                      : 'border-[#E5E5E3] hover:border-[#CCC] bg-white'}`}
                  >
                    {option}
                    {selected && ' ✓'}
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {(current.type === 'select' || current.type === 'multi') && current.id !== 2 && current.options?.map(option => {
          const isSelected = current.type === 'multi' 
            ? (currentAnswer as string[] || []).includes(option)
            : currentAnswer === option;
          
          return (
            <button
              key={option}
              onClick={() => handleAnswer(option)}
              className={`w-full text-left p-5 rounded-2xl border text-lg transition-all ${isSelected 
                ? 'border-[#0A66C2] bg-[#F0F7FF] text-[#111]' 
                : 'border-[#E5E5E3] hover:border-[#CCC] bg-white'}`}
            >
              {option}
              {current.type === 'multi' && isSelected && ' ✓'}
            </button>
          );
        })}
      </div>

      <div className="flex gap-3">
        {currentStep > 1 && (
          <button onClick={prev} className="btn-secondary flex-1 py-3">Back</button>
        )}
        <button 
          onClick={next} 
          disabled={!hasAnswer || isGenerating}
          className="btn-primary flex-1 py-3 disabled:opacity-50"
        >
          {currentStep === steps.length ? (isGenerating ? 'Generating...' : 'Generate plan') : 'Next'}
        </button>
      </div>
    </div>
  );
}
