"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface Step {
  id: number;
  question: string;
  options?: string[];
  type: 'select' | 'text' | 'multi';
}

const steps: Step[] = [
  { id: 1, question: "What's your industry or main business area?", type: 'text' },
  { id: 2, question: "Rough company size (revenue or team)?", options: ["Under $2M / <10 people", "$2M–$10M / 10-50 people", "$10M+ / 50+ people"], type: 'select' },
  { id: 3, question: "Biggest AI-related pain right now?", options: ["Too many tools, no clear wins", "Operations are manual and slow", "Marketing/leads not scaling", "Team overwhelmed by hype vs. results"], type: 'multi' },
  { id: 4, question: "Timeline for seeing real impact?", options: ["Next 30-60 days", "Next quarter", "6+ months"], type: 'select' },
];

export default function PlanningWizard() {
  const [currentStep, setCurrentStep] = useState(1);
  const [answers, setAnswers] = useState<Record<number, string | string[]>>({});
  const [generatedPlan, setGeneratedPlan] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [checkoutStep, setCheckoutStep] = useState<'plan' | 'checkout' | 'success'>('plan');
  const [checkoutEmail, setCheckoutEmail] = useState('');

  const current = steps.find(s => s.id === currentStep)!;

  const handleAnswer = (value: string) => {
    setAnswers(prev => {
      if (current.type === 'multi') {
        const currentVals = (prev[current.id] as string[]) || [];
        const newVals = currentVals.includes(value) 
          ? currentVals.filter(v => v !== value) 
          : [...currentVals, value];
        return { ...prev, [current.id]: newVals };
      }
      return { ...prev, [current.id]: value };
    });
  };

  const next = () => {
    if (currentStep < steps.length) {
      setCurrentStep(currentStep + 1);
    } else {
      generatePlan();
    }
  };

  const prev = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  const generatePlan = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      const industry = answers[1] || 'your business';
      const size = answers[2] || 'your size';
      const pains = (answers[3] as string[] || []).join(' + ') || 'core inefficiencies';
      const timeline = answers[4] || 'soon';

      const plan = `Initial AI Roadmap — generated by betterwithai system

For: ${industry} (${size})
Key pains: ${pains}
Timeline: ${timeline}

Prioritized wins (ROI ranked):
1. Quick-win automation: 18-30 hrs/mo back. Lead qualification or ops dispatch agent. High impact, low lift.
2. Process intelligence: AI surfaces patterns across your tools & data.
3. Client-facing leverage: Self-serve experiences or agents so you scale without adding headcount.

What the full Roadmap will include:
• Detailed audit of ops, marketing, tools
• Exact tools + build order with cost/benefit
• 60-min walkthrough call
• Written deliverable + 30-day support path

This site + Ops Leader just did the heavy planning lift. The paid Roadmap goes much deeper with your real data.`;

      setGeneratedPlan(plan);
      setIsGenerating(false);
      setCheckoutStep('plan');
    }, 1100);
  };

  const reset = () => {
    setCurrentStep(1);
    setAnswers({});
    setGeneratedPlan(null);
    setCheckoutStep('plan');
    setCheckoutEmail('');
  };

  if (generatedPlan) {
    return (
      <div className="max-w-[720px] mx-auto">
        <div className="mb-6">
          <div className="text-[#C6FF3A] text-xs tracking-[2px] mb-1">YOUR PLAN</div>
          <h3 className="text-3xl font-semibold tracking-tight">The configurator built this for you.</h3>
        </div>

        <div className="bg-[#0A0A0C] border border-white/10 p-8 rounded-3xl text-[14px] leading-relaxed text-[#D1D1D6] font-mono whitespace-pre-wrap mb-8">
{generatedPlan}
        </div>

        <div className="text-center">
          <a 
            href={`/portal?demoLogin=acme&newProject=true${checkoutEmail ? `&email=${encodeURIComponent(checkoutEmail)}` : ''}`}
            className="btn-primary inline-flex text-lg px-12 py-4"
          >
            Buy the Roadmap — $2,497
          </a>
          <div className="mt-3 text-xs text-[#5A5A5F]">One click. Live in the portal immediately.</div>

          <button onClick={reset} className="mt-4 text-sm text-[#5A5A5F] hover:text-white">Start over</button>
        </div>
      </div>
    );
  }

  const currentAnswer = answers[current.id];
  const hasAnswer = current.type === 'multi' 
    ? (currentAnswer as string[] || []).length > 0 
    : !!currentAnswer;

  return (
    <div className="max-w-[620px] mx-auto card p-8">
      <div className="mb-8">
        <div className="text-[#C6FF3A] text-xs tracking-[2px] mb-1">STEP {currentStep} OF {steps.length}</div>
        <h3 className="text-3xl font-semibold tracking-tight">{current.question}</h3>
      </div>

      <div className="space-y-2 mb-8">
        {current.type === 'text' && (
          <input 
            type="text" 
            className="w-full bg-[#0A0A0C] border border-white/10 p-5 rounded-2xl text-lg placeholder:text-white/40 focus:outline-none focus:border-[#C6FF3A]"
            placeholder="Type your answer..."
            value={(currentAnswer as string) || ''}
            onChange={(e) => handleAnswer(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter' && hasAnswer) next(); }}
          />
        )}

        {(current.type === 'select' || current.type === 'multi') && current.options?.map(option => {
          const isSelected = current.type === 'multi' 
            ? (currentAnswer as string[] || []).includes(option)
            : currentAnswer === option;
          
          return (
            <button
              key={option}
              onClick={() => handleAnswer(option)}
              className={`w-full text-left p-5 rounded-2xl border text-lg transition-all ${isSelected 
                ? 'border-[#C6FF3A] bg-[#C6FF3A]/5 text-white' 
                : 'border-white/10 hover:border-white/20 bg-white/5'}`}
            >
              {option}
              {current.type === 'multi' && isSelected && ' ✓'}
            </button>
          );
        })}
      </div>

      <div className="flex gap-3">
        {currentStep > 1 && (
          <button onClick={prev} className="btn-secondary flex-1 py-3">Back</button>
        )}
        <button 
          onClick={next} 
          disabled={!hasAnswer || isGenerating}
          className="btn-primary flex-1 py-3 disabled:opacity-50"
        >
          {currentStep === steps.length ? (isGenerating ? 'Generating...' : 'Generate plan') : 'Next'}
        </button>
      </div>
    </div>
  );
}
