"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface Step {
  id: number;
  question: string;
  options?: string[];
  type: 'select' | 'text' | 'multi';
}

const steps: Step[] = [
  { id: 1, question: "What's your industry or main business area?", type: 'text' },
  { id: 2, question: "Rough company size (revenue or team)?", options: ["Under $2M / <10 people", "$2M–$10M / 10-50 people", "$10M+ / 50+ people"], type: 'select' },
  { id: 3, question: "Biggest AI-related pain right now?", options: ["Too many tools, no clear wins", "Operations are manual and slow", "Marketing/leads not scaling", "Team overwhelmed by hype vs. results"], type: 'multi' },
  { id: 4, question: "Timeline for seeing real impact?", options: ["Next 30-60 days", "Next quarter", "6+ months"], type: 'select' },
];

export default function PlanningWizard() {
  const [currentStep, setCurrentStep] = useState(1);
  const [answers, setAnswers] = useState<Record<number, string | string[]>>({});
  const [generatedPlan, setGeneratedPlan] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [checkoutStep, setCheckoutStep] = useState<'plan' | 'checkout' | 'success'>('plan');
  const [checkoutEmail, setCheckoutEmail] = useState('');

  const current = steps.find(s => s.id === currentStep)!;

  const handleAnswer = (value: string) => {
    setAnswers(prev => {
      if (current.type === 'multi') {
        const currentVals = (prev[current.id] as string[]) || [];
        const newVals = currentVals.includes(value) 
          ? currentVals.filter(v => v !== value) 
          : [...currentVals, value];
        return { ...prev, [current.id]: newVals };
      }
      return { ...prev, [current.id]: value };
    });
  };

  const next = () => {
    if (currentStep < steps.length) {
      setCurrentStep(currentStep + 1);
    } else {
      generatePlan();
    }
  };

  const prev = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  const generatePlan = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      const industry = answers[1] || 'your business';
      const size = answers[2] || 'your size';
      const pains = (answers[3] as string[] || []).join(' + ') || 'core inefficiencies';
      const timeline = answers[4] || 'soon';

      const plan = `Initial AI Roadmap — generated by betterwithai system

For: ${industry} (${size})
Key pains: ${pains}
Timeline: ${timeline}

Prioritized wins (ROI ranked):
1. Quick-win automation: 18-30 hrs/mo back. Lead qualification or ops dispatch agent. High impact, low lift.
2. Process intelligence: AI surfaces patterns across your tools & data.
3. Client-facing leverage: Self-serve experiences or agents so you scale without adding headcount.

What the full Roadmap will include:
• Detailed audit of ops, marketing, tools
• Exact tools + build order with cost/benefit
• 60-min walkthrough call
• Written deliverable + 30-day support path

This site + Ops Leader just did the heavy planning lift. The paid Roadmap goes much deeper with your real data.`;

      setGeneratedPlan(plan);
      setIsGenerating(false);
      setCheckoutStep('plan');
    }, 1100);
  };

  const reset = () => {
    setCurrentStep(1);
    setAnswers({});
    setGeneratedPlan(null);
    setCheckoutStep('plan');
    setCheckoutEmail('');
  };

  if (generatedPlan) {
    return (
      <div className="card p-9 border border-[#C6FF3A]/30">
        <div className="uppercase text-xs tracking-[3px] text-[#C6FF3A] mb-1">INITIAL PLAN GENERATED BY THE SYSTEM</div>
        <h3 className="text-3xl font-semibold tracking-[-1px] mb-6">Here&apos;s what the website figured out for you.</h3>

        <div className="bg-[#0A0A0C] border border-[#222225] p-8 rounded-2xl text-sm leading-relaxed text-[#D1D1D6] font-mono whitespace-pre-wrap">
{generatedPlan}
        </div>

        <AnimatePresence mode="wait">
          {checkoutStep === 'plan' && (
            <motion.div 
              key="plan-actions"
              initial={{ opacity: 0, y: 10 }} 
              animate={{ opacity: 1, y: 0 }}
              className="mt-8"
            >
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <button 
                  onClick={() => setCheckoutStep('checkout')}
                  className="btn-primary text-lg py-[21px] justify-center tracking-[-0.2px]"
                >
                  Buy now — $2,497 (like ordering a Tesla) →
                </button>
                <button onClick={reset} className="btn-secondary text-lg py-5">Change answers</button>
              </div>
              <p className="mt-4 text-center text-sm text-white/70">One click. Contract auto-created. Live in your portal immediately. <span className="text-[#C6FF3A]">No call required.</span></p>
            </motion.div>
          )}

          {checkoutStep === 'checkout' && (
            <motion.div 
              key="checkout"
              initial={{ opacity: 0, y: 10 }} 
              animate={{ opacity: 1, y: 0 }}
              className="mt-8 border border-white/10 bg-[#0B0B0F] rounded-2xl p-7"
            >
              <div className="text-sm text-[#C6FF3A] tracking-widest mb-1">SECURE CHECKOUT</div>
              <div className="flex items-baseline justify-between mb-6">
                <div>
                  <div className="font-semibold text-xl">AI Roadmap — Full Deliverable</div>
                  <div className="text-white/60 text-sm">One-time • Fully self-serve. Zero calls.</div>
                </div>
                <div className="text-4xl font-bold tracking-[-1px]">$2,497</div>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="block text-xs tracking-widest text-white/50 mb-1.5">EMAIL (for portal access)</label>
                  <input 
                    type="email" 
                    value={checkoutEmail} 
                    onChange={(e) => setCheckoutEmail(e.target.value)}
                    placeholder="you@yourcompany.com"
                    className="w-full bg-white/5 border border-white/15 p-3.5 rounded-xl text-white placeholder:text-white/40 focus:border-[#C6FF3A]"
                  />
                </div>
              </div>

              <button 
                onClick={() => {
                  // Simulate secure checkout processing like Tesla order
                  setTimeout(() => {
                    setCheckoutStep('success');
                  }, 1200);
                }}
                disabled={!checkoutEmail.includes('@')}
                className="btn-primary w-full mt-6 py-4 text-lg disabled:opacity-60"
              >
                {checkoutEmail ? 'Complete purchase' : 'Enter email to continue'}
              </button>

              <p className="text-[10px] text-center text-white/40 mt-3">Preview checkout. You’ll land in the portal with your project.</p>
            </motion.div>
          )}

          {checkoutStep === 'success' && (
            <motion.div 
              key="success"
              initial={{ opacity: 0, scale: 0.98 }} 
              animate={{ opacity: 1, scale: 1 }}
              className="mt-8 text-center bg-[#C6FF3A]/10 border border-[#C6FF3A]/30 rounded-2xl p-8"
            >
              <div className="text-4xl mb-2">✅</div>
              <div className="text-2xl font-semibold tracking-tight mb-1">Payment successful</div>
              <p className="text-white/70">Contract generated. Your project is live in the portal. No call required.</p>

              <a 
                href={`/portal?demoLogin=acme&newProject=true${checkoutEmail ? `&email=${encodeURIComponent(checkoutEmail)}` : ''}`} 
                className="btn-primary mt-6 inline-flex text-lg px-10 py-4"
              >
                Go to my portal now →
              </a>

              <button onClick={reset} className="block mx-auto mt-4 text-sm text-white/50 hover:text-white">Start another plan</button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    );
  }

  const currentAnswer = answers[current.id];
  const hasAnswer = current.type === 'multi' 
    ? (currentAnswer as string[] || []).length > 0 
    : !!currentAnswer;

  return (
    <div className="card p-8">
      <div className="flex justify-between items-center mb-6">
        <div>
          <span className="text-[#C6FF3A] text-sm">STEP {currentStep} of {steps.length}</span>
          <h3 className="text-2xl font-semibold mt-1">{current.question}</h3>
        </div>
        <div className="text-xs text-white/50">The website planner</div>
      </div>

      <div className="space-y-3 mb-8">
        {current.type === 'text' && (
          <input 
            type="text" 
            className="w-full bg-white/5 border border-white/10 p-4 rounded-lg text-white placeholder:text-white/40 focus:outline-none focus:border-[#C6FF3A]"
            placeholder="Type your answer..."
            value={(currentAnswer as string) || ''}
            onChange={(e) => handleAnswer(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter' && hasAnswer) next(); }}
          />
        )}

        {(current.type === 'select' || current.type === 'multi') && current.options?.map(option => {
          const isSelected = current.type === 'multi' 
            ? (currentAnswer as string[] || []).includes(option)
            : currentAnswer === option;
          
          return (
            <button
              key={option}
              onClick={() => handleAnswer(option)}
              className={`w-full text-left p-4 rounded-lg border transition-all ${isSelected 
                ? 'border-[#C6FF3A] bg-[#C6FF3A]/10' 
                : 'border-white/10 hover:border-white/30 bg-white/5'}`}
            >
              {option}
              {current.type === 'multi' && isSelected && ' ✓'}
            </button>
          );
        })}
      </div>

      <div className="flex gap-4">
        {currentStep > 1 && (
          <button onClick={prev} className="btn-secondary flex-1">Back</button>
        )}
        <button 
          onClick={next} 
          disabled={!hasAnswer || isGenerating}
          className="btn-primary flex-1 disabled:opacity-50"
        >
          {currentStep === steps.length ? (isGenerating ? 'Generating plan...' : 'Generate My Initial Plan') : 'Next'}
        </button>
      </div>

      <p className="mt-6 text-xs text-center text-white/50">
        This is the website doing the skilled planning work. Real Roadmap goes much deeper with your actual data.
      </p>
    </div>
  );
}
